# Project wide metadata-files: 

bibliography: 
  - resources/bibliography.bib  
  - "resources/fromDOI.bib" # this file is created by doi2cite.lua




filters:
  - resources/doi2cite.lua
  - quarto

# if you prefer another style
csl: https://raw.githubusercontent.com/citation-style-language/styles/0749a19b8306f2e8dcb9bf1a2e3a6992666030ac/nature.csl


#project:
#  output-dir: output
# Does not work correctly with publish

toc: true

format:
  html:
    #theme: [sandstone, ../custom.scss]
    backgroundcolor: white
    page-layout: full
    number-sections: true

  docx: default

  # typst:
  #   papersize: a4
  #   number-sections: true
  #   shift-heading-level-by: 0
  #   citeproc: false
  #   mainfont: "Palatino"
  #   cls: nature # no online path
  #   bibliography:
  #     - "resources/fromDOI.bib" # only one file 


  pdf:
    papersize: a4
    geometry:
      - margin=1in
    linestretch: 1.25
    fontfamily: palatino # Palatino https://www.overleaf.com/learn/latex/Font_typefaces
    keep-tex: true
    number-sections: false
    colorlinks: false
    cite-method: biblatex # ciations with latex
