on:
  push:
    branches: main

name: Render and Publish

# you need these permissions to publish to GitHub pages
permissions:
  contents: write
  pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book
          tinytex: true
          # uncomment below and fill to pin a version
          # version: SPECIFIC-QUARTO-VERSION-HERE

      - name: Render html
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html

      - name: Upload html
        uses: actions/upload-artifact@v3
        with:
          name: manuscript.html
          path: writing/manuscript.html

      - name: Render all formats
        uses: quarto-dev/quarto-actions/render@v2

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: manuscript.pdf
          path: writing/manuscript.pdf

      # - name: Publish HTML
      #   uses: quarto-dev/quarto-actions/publish@v2
      #   with:
      #     target: gh-pages
      #     render: false
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions

      # add software dependencies here and any libraries

      # From https://github.com/actions/setup-python
      # - name: Setup Python
      #   uses: actions/setup-python@v3
